# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceLauncher' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SpaceLauncher

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

end
