default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #increment_build_number(xcodeproj: "SpaceViewer.xcodeproj")
    #build_app(workspace: "SpaceViewer.xcworkspace", scheme: "SpaceViewer")
    #upload_to_testflight

    #match(type: "appstore", readonly: is_ci)
    gym(scheme: "SpaceViewer")
  end
end
