name: basic node setup

on: [push, pull_request]

jobs:
  node-lint-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]
        node: [10, 12]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: install node_modules
      run: yarn install --frozen-lockfile

    - name: node lint
      run:
        yarn lint-check

    - name: node test
      run:
        yarn workspace mobile test-ci

    # - name: bundle test
    #   run:
    #     npx react-native bundle --entry-file packages/mobile/index.js --bundle-output /dev/null
